Repository sssmoker/SMOKER-FE, pull requests merged in 2025-02, with the labels that each got.

#21 Init: query
  package-lock.json
  package.json
  src/main.jsx
  src/pages/HomePage.jsx
Labels: documentation

#20 fix: 잡다한 오류 및 불필요 코드 삭제
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmessage.txt
  eslint.config.js
  src/Router.jsx
  src/components/common/Navbar.jsx
  src/pages/HomePage.jsx
  src/pages/smoking-area/SmokingAreaDetailPage.jsx
  src/pages/smoking-area/SmokingAreaPage.jsx
  src/pages/smoking-area/SmokingAreaReviewPage.jsx
  tailwind.config.js
  vite.config.js
Labels: help wanted

#19 feat: 목록보기 페이지, 히스토리 페이지, 정보 수정 페이지
  db.json
  src/Router.jsx
  src/components/area-list/card-list/ImgCard.jsx
  src/components/area-list/card-list/ImgList.jsx
  src/components/area-list/card-list/SmokingAreaCard.jsx
  src/components/area-list/card-list/SmokingAreaList.jsx
  src/components/area-list/filter/Filter.jsx
  src/components/smoking-area/review/FloatingButton.jsx
  src/components/smoking-area/review/ReviewCard.jsx
  src/components/smoking-area/review/StarRatingStatistics.jsx
  src/components/smoking-area/upper-info/SmokingAreaInfo.jsx
  src/components/smoking-area/upper-info/Topbar.jsx
  src/components/smoking-area/upper-info/UpdateButton.jsx
  src/components/smoking-history/HistoryCard.jsx
  src/components/smoking-update/OptionsSelection.jsx
  src/data/smokingAreaListDummy.js
  src/pages/ListPage.jsx
  src/pages/smoking-area/SmokingAreaDetailPage.jsx
  src/pages/smoking-area/SmokingAreaHistoryPage.jsx
  src/pages/smoking-area/SmokingAreaPage.jsx
  src/pages/smoking-area/SmokingAreaReviewPage.jsx
  src/pages/smoking-area/SmokingAreaUpdatePage.jsx
  tailwind.config.js
Labels: enhancement

#18 feat: homepage 내주변 버튼 활성화 + 토스트 모달
  eslint.config.js
  package-lock.json
  package.json
  src/assets/Property 1=상세위치아이콘.svg
  src/assets/Property 1=홈화면, Property 2=지도버튼.svg
  src/assets/Property 1=흡연구역등록아이콘.svg
  src/assets/sample-image.png
  src/assets/목록보기버튼.svg
  src/assets/사용자위치아이콘.svg
  src/components/HomeMap/Map.jsx
  src/components/HomeMap/Marker.jsx
  src/components/HomeMap/MarkerInfoCard.jsx
  src/components/HomeMap/MarkerPopup.jsx
  src/components/common/AroundMeBtn.jsx
  src/components/common/AroundMeButton.jsx
  src/components/common/Navbar.jsx
  src/components/common/SearchBar.jsx
  src/components/common/toast/AgreementToast.jsx
  src/components/common/toast/Toast.jsx
  src/hooks/useLocation.jsx
  src/layouts/root-layout.jsx
  src/pages/HomePage.jsx
  src/pages/X-UpdateCompletePage.jsx
  src/pages/add-smoking-area/RegisterSmokingArea.jsx
Labels: bug

#22 Feat: 데이터 변수 이름 수정 및 api 테스트
  .env
  .gitignore
  db.json
  src/components/area-list/card-list/SmokingAreaCard.jsx
  src/components/area-list/card-list/SmokingAreaList.jsx
  src/components/smoking-area/review/ReviewCard.jsx
  src/components/smoking-area/review/StarRatingStatistics.jsx
  src/components/smoking-area/upper-info/SmokingAreaInfo.jsx
  src/components/smoking-history/HistoryCard.jsx
  src/data/smokingAreaListDummy.js
  src/pages/ListPage.jsx
  src/pages/smoking-area/SmokingAreaDetailPage.jsx
  src/pages/smoking-area/SmokingAreaHistoryPage.jsx
  src/pages/smoking-area/SmokingAreaPage.jsx
  src/pages/smoking-area/SmokingAreaReviewPage.jsx
  src/pages/smoking-area/SmokingAreaUpdatePage.jsx
  src/utils/api.js
  src/utils/queries.js
Labels: enhancement

#24 design: loginpage 상단 디자인 수정(애니메이션)
  src/pages/auth/LoginPage.jsx
  tailwind.config.js
Labels: enhancement

#26 Feat: api 쿼리대로 api 연결 수정중
  .env.production
  .gitignore
  src/components/smoking-area/upper-info/SmokingAreaInfo.jsx
  src/pages/ListPage.jsx
  src/pages/smoking-area/SmokingAreaDetailPage.jsx
  src/pages/smoking-area/SmokingAreaHistoryPage.jsx
  src/pages/smoking-area/SmokingAreaPage.jsx
  src/utils/api.js
  src/utils/queries.js
Labels: enhancement

#29 Feat/connect login api
  src/Router.jsx
  src/pages/auth/GoogleOAuth2.js
  src/pages/auth/GoogleOAuth2RedirectHandler.jsx
  src/pages/auth/KakaoOAuth.js
  src/pages/auth/KakaoOAuthRedirectHandler.jsx
  src/pages/auth/LoginPage.jsx
  src/pages/auth/MyPage.jsx
  src/redux/actions/authAciton.js
  src/redux/actions/authAction.js
  src/redux/reducers/authReducer.js
  src/utils/api.js
  src/utils/queries.js
Labels: enhancement

#31 Api/home
  .env.production
  src/components/HomeMap/Map.jsx
  src/components/HomeMap/MarkerPopup.jsx
  src/hooks/useMapQueries.js
  src/pages/HomePage.jsx
  src/pages/auth/GoogleOAuth2.js
  src/utils/api.js
Labels: bug, enhancement

#32 Refactor/list smoking area
  src/components/area-list/card-list/SmokingAreaCard.jsx
  src/components/area-list/card-list/SmokingAreaList.jsx
  src/components/smoking-area/review/ReviewCard.jsx
  src/components/smoking-area/review/StarRatingStatistics.jsx
  src/mock/listDummy.js
  src/mock/smokingAreaDetailDummy.js
  src/mock/smokingAreaHistoryDummy.js
  src/mock/smokingAreaReviewsDummy.js
  src/mock/smokingAreaStarInfoDummy.js
  src/pages/ListPage.jsx
  src/pages/favorites/SavedSmokingAreasPage.jsx
  src/pages/smoking-area/SmokingAreaHistoryPage.jsx
  src/pages/smoking-area/SmokingAreaPage.jsx
  src/pages/smoking-area/SmokingAreaUpdatePage.jsx
  src/utils/api.js
Labels: bug

#33 feat: 흡연구역 등록 절차 및 수정 절차 프로토타입 구현
  src/components/common/toast/Toast.jsx
  src/components/smoking-add/completeToast.jsx
  src/components/smoking-area/review/completeToast.jsx
  src/components/smoking-update/OptionsSelection.jsx
  src/pages/add-smoking-area/AddSmokingAreaImagePage.jsx
  src/pages/add-smoking-area/AddSmokingAreaNamePage.jsx
  src/pages/add-smoking-area/RegisterSmokingArea.jsx
  src/pages/auth/KakaoOAuth.js
  src/pages/smoking-area/SmokingAreaUpdatePage.jsx
  src/utils/api.js
Labels: enhancement

#35 Feat/ my-page & login
  src/pages/auth/KakaoOAuth.js
  src/redux/actions/authAction.js
Labels: enhancement

#38 refactor: mypage 데이터 연결 완료, 외부폼 이동가능, 로직 수정
  db.json
  src/components/member-info/DetailSection.jsx
  src/components/member-info/ProfileSection.jsx
  src/components/member-info/ReviewSection.jsx
  src/pages/auth/EditNamePage.jsx
  src/pages/auth/MyPage.jsx
Labels: enhancement

#39 ✨: 홈화면 검색바
  src/components/common/AroundMeButton.jsx
  src/components/common/SearchBar.jsx
Labels: enhancement

#41 bug: zoom level 오류 해결
  src/components/HomeMap/Map.jsx
  src/components/HomeMap/MarkerInfoCard.jsx
  src/components/HomeMap/MarkerPopup.jsx
  src/components/smoking-add/RegisterMap.jsx
  src/pages/HomePage.jsx
  src/utils/calculateDistance.js
Labels: enhancement
